export enum TASK_MANAGER_EVENT {
    TASK_QUEUED = "TASK_QUEUED",
    TASK_STARTING = "TASK_STARTING",
    TASK_COMPLETED = "TASK_COMPLETED",
    ERROR = "ERROR",
}

export enum TASK_MANAGER_ERROR {
    UNEXPECTED = "UNEXPECTED",
    TASK_EXECUTION_ERROR = "TASK_EXECUTION_ERROR",
    TASK_TIMEOUT_ERROR = "TASK_TIMEOUT_ERROR",
    TASK_ADDING_ERROR = "TASK_ADDING_ERROR",
    TASK_ABORTING_ERROR = "TASK_ABORTING_ERROR",
}
